list(APPEND blade_cuda_files
source/blade/src/bonded/bonded.cu
source/blade/src/bonded/bonded.h
source/blade/src/bonded/pair.cu
source/blade/src/bonded/pair.h
source/blade/src/domdec/assign_blocks.cu
source/blade/src/domdec/assign_domain.cu
source/blade/src/domdec/assign_excl.cu
source/blade/src/domdec/cull.cu
source/blade/src/domdec/domdec.cu
source/blade/src/domdec/domdec.h
source/blade/src/domdec/recull.cu
source/blade/src/holonomic/holonomic.cu
source/blade/src/holonomic/holonomic.h
source/blade/src/holonomic/virtual.cu
source/blade/src/holonomic/virtual.h
source/blade/src/holonomic/rectify.cu
source/blade/src/holonomic/rectify.h
source/blade/src/msld/msld.cu
source/blade/src/msld/msld.h
source/blade/src/nbdirect/nbdirect.cu
source/blade/src/nbdirect/nbdirect.h
source/blade/src/nbrecip/nbrecip.cu
source/blade/src/nbrecip/nbrecip.h
source/blade/src/restrain/restrain.cu
source/blade/src/restrain/restrain.h
source/blade/src/rng/rng_gpu.cu
source/blade/src/rng/rng_gpu.h
source/blade/src/run/run.cu
source/blade/src/run/run.h
source/blade/src/update/minimize.cu
source/blade/src/update/pressure.cu
source/blade/src/update/pressure.h
source/blade/src/update/update.cu
)
