list(APPEND blade_cxx_files
source/blade/src/io/calculate.cxx
source/blade/src/io/calculate.h
source/blade/src/io/control.cxx
source/blade/src/io/control.h
source/blade/src/io/io.cxx
source/blade/src/io/io.h
source/blade/src/io/variables.cxx
source/blade/src/io/variables.h
source/blade/src/main/defines.h
source/blade/src/main/real3.h
source/blade/src/rng/rng_cpu.cxx
source/blade/src/rng/rng_cpu.h
source/blade/src/system/coordinates.cxx
source/blade/src/system/coordinates.h
source/blade/src/system/parameters.cxx
source/blade/src/system/parameters.h
source/blade/src/system/potential.cxx
source/blade/src/system/potential.h
source/blade/src/system/selections.cxx
source/blade/src/system/selections.h
source/blade/src/system/state.cxx
source/blade/src/system/state.h
source/blade/src/system/structure.cxx
source/blade/src/system/structure.h
source/blade/src/system/system.cxx
source/blade/src/system/system.h
source/blade/src/xdr/xdrfile.cxx
source/blade/src/xdr/xdrfile.h
source/blade/src/xdr/xdrfile_xtc.cxx
source/blade/src/xdr/xdrfile_xtc.h
)
