list(APPEND domdec_cuda_files
  source/domdec/Bonded.cu
  source/domdec/Bonded.h
  source/domdec/MDsim.cu
  source/domdec/MDsim.h
  source/domdec/NBdirect.cu
  source/domdec/NBdirect.h
  source/domdec/NBrecip.cu
  source/domdec/NBrecip.h
  source/domdec/Nlist.cu
  source/domdec/Nlist.h
  source/domdec/bonded_gpu.cu
  source/domdec/domdec_gpu.cu
  source/domdec/domdec_gpu.h
  source/domdec/domdec_gpu_dyna.cu
  source/domdec/domdec_util_gpu.cu
  source/domdec/enb_core_gpu.cu
  source/domdec/nblist_tilex_gpu.cu
  source/domdec/nbrecip_gpu.cu
  source/domdec_gpu/Bonded_struct.h
  source/domdec_gpu/Bspline.cu
  source/domdec_gpu/Bspline.h
  source/domdec_gpu/CudaBlock.cu
  source/domdec_gpu/CudaBlock.h
  source/domdec_gpu/CudaBondedForce.cu
  source/domdec_gpu/CudaBondedForce.h
  source/domdec_gpu/CudaDirectForce14_util.h
  source/domdec_gpu/CudaDirectForceKernels.cu
  source/domdec_gpu/CudaDirectForceKernels.h
  source/domdec_gpu/CudaDirectForceTypes.h
  source/domdec_gpu/CudaDirectForce_util.h
  source/domdec_gpu/CudaDomdecRecip.h
  source/domdec_gpu/CudaEnergyVirial.cu
  source/domdec_gpu/CudaEnergyVirial.h
  source/domdec_gpu/CudaNeighborList.cu
  source/domdec_gpu/CudaNeighborList.h
  source/domdec_gpu/CudaNeighborListBuild.cu
  source/domdec_gpu/CudaNeighborListBuild.h
  source/domdec_gpu/CudaNeighborListSort.cu
  source/domdec_gpu/CudaNeighborListSort.h
  source/domdec_gpu/CudaNeighborListStruct.h
  source/domdec_gpu/CudaPMEDirectForce.cu
  source/domdec_gpu/CudaPMEDirectForce.h
  source/domdec_gpu/CudaPMEDirectForceBlock.cu
  source/domdec_gpu/CudaPMEDirectForceBlock.h
  source/domdec_gpu/CudaPMERecip.cu
  source/domdec_gpu/CudaPMERecip.h
  source/domdec_gpu/CudaTopExcl.cu
  source/domdec_gpu/CudaTopExcl.h
  source/domdec_gpu/DomdecRecip.h
  source/domdec_gpu/Force.cu
  source/domdec_gpu/Force.h
  source/domdec_gpu/Matrix3d.cu
  source/domdec_gpu/Matrix3d.h
  source/domdec_gpu/XYZ.h
  source/domdec_gpu/XYZQ.cu
  source/domdec_gpu/XYZQ.h
  source/domdec_gpu/cudaXYZ.h
  source/domdec_gpu/cuda_pme_gather.h
  source/domdec_gpu/cuda_pme_selfe.h
  source/domdec_gpu/cuda_pme_spread.h
  source/domdec_gpu/cuda_utils.cu
  source/domdec_gpu/cuda_utils.h
  source/domdec_gpu/gpu_utils.h
  source/domdec_gpu/hostXYZ.h
  source/domdec_gpu/reduce.cu
  source/domdec_gpu/reduce.h)
